// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: recall-importer/v1/recall-importer.proto

package pb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetExampleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Speaker       string                 `protobuf:"bytes,1,opt,name=speaker,proto3" json:"speaker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExampleRequest) Reset() {
	*x = GetExampleRequest{}
	mi := &file_recall_importer_v1_recall_importer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExampleRequest) ProtoMessage() {}

func (x *GetExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recall_importer_v1_recall_importer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExampleRequest.ProtoReflect.Descriptor instead.
func (*GetExampleRequest) Descriptor() ([]byte, []int) {
	return file_recall_importer_v1_recall_importer_proto_rawDescGZIP(), []int{0}
}

func (x *GetExampleRequest) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

type GetExampleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExampleResponse) Reset() {
	*x = GetExampleResponse{}
	mi := &file_recall_importer_v1_recall_importer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExampleResponse) ProtoMessage() {}

func (x *GetExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recall_importer_v1_recall_importer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExampleResponse.ProtoReflect.Descriptor instead.
func (*GetExampleResponse) Descriptor() ([]byte, []int) {
	return file_recall_importer_v1_recall_importer_proto_rawDescGZIP(), []int{1}
}

var File_recall_importer_v1_recall_importer_proto protoreflect.FileDescriptor

const file_recall_importer_v1_recall_importer_proto_rawDesc = "" +
	"\n" +
	"(recall-importer/v1/recall-importer.proto\x12\x12recall_importer.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\x1a$gnostic/openapi/v3/annotations.proto\"2\n" +
	"\x11GetExampleRequest\x12\x1d\n" +
	"\aspeaker\x18\x01 \x01(\tB\x03\xe0A\bR\aspeaker\"\x14\n" +
	"\x12GetExampleResponse2\xcf\x01\n" +
	"\x15RecallImporterService\x12\xb5\x01\n" +
	"\n" +
	"GetExample\x12%.recall_importer.v1.GetExampleRequest\x1a&.recall_importer.v1.GetExampleResponse\"X\xbaGB\n" +
	"\aexample\x12\x14Get example response\x1a!Returns an empty example response\x82\xd3\xe4\x93\x02\r\x12\v/v1/exampleB\xc4\x01\xbaG\x87\x01\x12=\n" +
	"\x13recall-importer-api\x12!Elasticsearch importer for Recall2\x031.0\x1a$\n" +
	"\x15http://localhost:8080\x12\vHost Server* :\x1e\n" +
	"\x1c\n" +
	"\tBasicAuth\x12\x0f\n" +
	"\r\n" +
	"\x04http*\x05basicZ7github.com/karafrorg/recall-importer/internal/pkg/pb;pbb\x06proto3"

var (
	file_recall_importer_v1_recall_importer_proto_rawDescOnce sync.Once
	file_recall_importer_v1_recall_importer_proto_rawDescData []byte
)

func file_recall_importer_v1_recall_importer_proto_rawDescGZIP() []byte {
	file_recall_importer_v1_recall_importer_proto_rawDescOnce.Do(func() {
		file_recall_importer_v1_recall_importer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recall_importer_v1_recall_importer_proto_rawDesc), len(file_recall_importer_v1_recall_importer_proto_rawDesc)))
	})
	return file_recall_importer_v1_recall_importer_proto_rawDescData
}

var file_recall_importer_v1_recall_importer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_recall_importer_v1_recall_importer_proto_goTypes = []any{
	(*GetExampleRequest)(nil),  // 0: recall_importer.v1.GetExampleRequest
	(*GetExampleResponse)(nil), // 1: recall_importer.v1.GetExampleResponse
}
var file_recall_importer_v1_recall_importer_proto_depIdxs = []int32{
	0, // 0: recall_importer.v1.RecallImporterService.GetExample:input_type -> recall_importer.v1.GetExampleRequest
	1, // 1: recall_importer.v1.RecallImporterService.GetExample:output_type -> recall_importer.v1.GetExampleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_recall_importer_v1_recall_importer_proto_init() }
func file_recall_importer_v1_recall_importer_proto_init() {
	if File_recall_importer_v1_recall_importer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recall_importer_v1_recall_importer_proto_rawDesc), len(file_recall_importer_v1_recall_importer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recall_importer_v1_recall_importer_proto_goTypes,
		DependencyIndexes: file_recall_importer_v1_recall_importer_proto_depIdxs,
		MessageInfos:      file_recall_importer_v1_recall_importer_proto_msgTypes,
	}.Build()
	File_recall_importer_v1_recall_importer_proto = out.File
	file_recall_importer_v1_recall_importer_proto_goTypes = nil
	file_recall_importer_v1_recall_importer_proto_depIdxs = nil
}
