// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: recall-importer/v1/recall-importer.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecallImporterService_GetExample_FullMethodName = "/recall_importer.v1.RecallImporterService/GetExample"
)

// RecallImporterServiceClient is the client API for RecallImporterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecallImporterServiceClient interface {
	GetExample(ctx context.Context, in *GetExampleRequest, opts ...grpc.CallOption) (*GetExampleResponse, error)
}

type recallImporterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecallImporterServiceClient(cc grpc.ClientConnInterface) RecallImporterServiceClient {
	return &recallImporterServiceClient{cc}
}

func (c *recallImporterServiceClient) GetExample(ctx context.Context, in *GetExampleRequest, opts ...grpc.CallOption) (*GetExampleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExampleResponse)
	err := c.cc.Invoke(ctx, RecallImporterService_GetExample_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecallImporterServiceServer is the server API for RecallImporterService service.
// All implementations must embed UnimplementedRecallImporterServiceServer
// for forward compatibility.
type RecallImporterServiceServer interface {
	GetExample(context.Context, *GetExampleRequest) (*GetExampleResponse, error)
	mustEmbedUnimplementedRecallImporterServiceServer()
}

// UnimplementedRecallImporterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecallImporterServiceServer struct{}

func (UnimplementedRecallImporterServiceServer) GetExample(context.Context, *GetExampleRequest) (*GetExampleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExample not implemented")
}
func (UnimplementedRecallImporterServiceServer) mustEmbedUnimplementedRecallImporterServiceServer() {}
func (UnimplementedRecallImporterServiceServer) testEmbeddedByValue()                               {}

// UnsafeRecallImporterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecallImporterServiceServer will
// result in compilation errors.
type UnsafeRecallImporterServiceServer interface {
	mustEmbedUnimplementedRecallImporterServiceServer()
}

func RegisterRecallImporterServiceServer(s grpc.ServiceRegistrar, srv RecallImporterServiceServer) {
	// If the following call pancis, it indicates UnimplementedRecallImporterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecallImporterService_ServiceDesc, srv)
}

func _RecallImporterService_GetExample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecallImporterServiceServer).GetExample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecallImporterService_GetExample_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecallImporterServiceServer).GetExample(ctx, req.(*GetExampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecallImporterService_ServiceDesc is the grpc.ServiceDesc for RecallImporterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecallImporterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recall_importer.v1.RecallImporterService",
	HandlerType: (*RecallImporterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExample",
			Handler:    _RecallImporterService_GetExample_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recall-importer/v1/recall-importer.proto",
}
